# NEW FILE
import re

class SymbolicLogicEngine:
    """
    The System 2 Symbolic Logic Engine (SLE).
    This engine safely parses and executes the cognitive programs
    generated by the System 1 neural network. It provides the
    verifiability and robustness required by the "weakness-free" mandate.
    """
    def __init__(self):
        # A whitelist of allowed characters and patterns for security
        self.allowed_pattern = re.compile(r"^[0-9\+\-\*\/\(\)\s]+$")
        print("[L3 SLE] Symbolic Logic Engine initialized and sandboxed.")

    def execute(self, program_str: str) -> (float, bool, str):
        """
        Safely executes a symbolic program.
        Returns: (result, success, error_message)
        """
        program_str = program_str.strip()
        
        # 1. Security Validation (Grammar Check)
        if not self.allowed_pattern.match(program_str):
            msg = "Syntax Error: Program contains disallowed characters."
            print(f"[L3 SLE] FAILED: {msg} (Program: '{program_str}')")
            return None, False, msg
            
        # 2. Safe Execution using a sandboxed eval
        try:
            # A final check to prevent dangerous operations
            if "__" in program_str:
                raise ValueError("Potentially malicious code detected.")
            
            result = eval(program_str)
            print(f"[L3 SLE] SUCCESS: Program '{program_str}' executed. Result: {result}")
            return float(result), True, ""
        except (SyntaxError, ZeroDivisionError, ValueError) as e:
            msg = f"Execution Error: {type(e).__name__}"
            print(f"[L3 SLE] FAILED: {msg} (Program: '{program_str}')")
            return None, False, msg
